# Instructions...

* There are additional cells after each code snippet, practice in it, you can create more using 'shift+Enter'
* prerequisite:- basic understanding of Python

# Numpy

 Importing library

In [1]:
import numpy as np

converting list to an array using **np.array(args)**

In [2]:
list = [1,2,3,4,5]

np.array(list)

array([1, 2, 3, 4, 5])

In [3]:
# example 2
matrix = [[1,2,3],[5,4,3],[5,6,7]]

np.array(matrix)

array([[1, 2, 3],
       [5, 4, 3],
       [5, 6, 7]])

** construct arrays of numbers**
  * using 'arange' function
  * **"np.arange( args )"**
  * np.arange( lower bound , upper bound , step size)
  * lowebound = from where to start
  * upperbound = where to finish
  * stepsize = how many numbers to skip e.g. 2,3

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10,2)
# it will skip two elements as the step size is 2

array([1, 3, 5, 7, 9])

In [52]:
 #to convert it to a float array
np.arange(1,10, dtype = float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [54]:
np.arange(5)**3
# it will create an array of cubes of 10 numbers

array([ 0,  1,  8, 27, 64], dtype=int32)

# using linspace(arg1,arg2,arg3)

   * The number of elements created is equal to the value of arg3 
   * It creates equally spaced elements between the specified beginning and end values

In [18]:
np.linspace(1,5,10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

** various methods of creating matices**
  
  * np.matrix()- creates matrix as per arguments
  * np.zeros() - creates matrices of all zeroes
  * np.ones()  - creates matrices of all ones
  * np.eye()   - creates identity matrix
  * np.empty() - creates array of 
  

In [20]:
np.matrix('1 2;3 4')

matrix([[1, 2],
        [3, 4]])

In [25]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [27]:
# to create a matrix we need to input size as single argument
np.zeros( (4,4) )
# this will create a matrix of 4x4

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.ones( (4,4) )

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [34]:
np.eye(4)
# it will create an identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [35]:
np.empty( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

# using reshape()

In [31]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(1,10).reshape(3,3)
# it will change its shape
# it may cause error if no. of elements and the shape doesn't fit..

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Basic operations on Arrays

In [37]:
a = np.array([1,2,1,2,1])
b = np.arange(5)
print(a)
print(b)

[1 2 1 2 1]
[0 1 2 3 4]


In [38]:
c = a - b

In [39]:
c

array([ 1,  1, -1, -1, -3])

In [40]:
c**2

array([1, 1, 1, 1, 9], dtype=int32)

In [42]:
c>1
# In this way we can check a condition on the elements of an array

array([False, False, False, False, False], dtype=bool)

In [43]:
# multiplication
c * a

array([ 1,  2, -1, -2, -3])

In [44]:
a = c * a
a * b

array([  0,   2,  -2,  -6, -12])

In [46]:
# to find out maximum no. of an array

#  syntax = array.max()
#           array.min()
    
a = np.array([1,2,3,4,5])
b = np.array([3,2,5,35,6])

print( a.max(),b.max(),a.min(),b.min() )

5 35 1 2


In [49]:
# to get the sum of the array

b.sum()

51

In [51]:
# for exponents
np.exp(a)

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ])